CREATE TABLE IF NOT EXISTS cities (
	id TINYINT(2) NOT NULL AUTO_INCREMENT,
	city_name VARCHAR(15) NOT NULL,
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE INDEX city_name (city_name)
) COMMENT='Города';
