CREATE TABLE IF NOT EXISTS stores (
	id TINYINT(2) NOT NULL AUTO_INCREMENT,
	identity CHAR(6) NOT NULL,
	city VARCHAR(15) NULL DEFAULT NULL,
	address VARCHAR(100) NULL DEFAULT NULL,
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE INDEX identity (identity),
	INDEX FK_stores_cities (city),
	CONSTRAINT FK_stores_cities FOREIGN KEY (city) REFERENCES cities (city_name) ON UPDATE CASCADE ON DELETE RESTRICT
) COMMENT='Магазины';
